#!/usr/bin/env python3
import csv
import io
import os
import secrets
from datetime import date, datetime
from functools import wraps
from pathlib import Path

import psycopg
from flask import Flask, Response, jsonify, redirect, request, session, url_for
from psycopg.rows import dict_row

from inventory_web_app import HTML


DATABASE_URL = os.environ.get("DATABASE_URL")
APP_PASSWORD = os.environ.get("APP_PASSWORD", "changeme")
APP_USERNAME = os.environ.get("APP_USERNAME", "admin")
SEED_PATH = Path(__file__).with_name("seed_products.csv")

app = Flask(__name__)
app.secret_key = os.environ.get("SECRET_KEY") or secrets.token_hex(32)


LOGIN_HTML = """<!doctype html>
<html lang="zh-Hant">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>擺攤收款紀錄登入</title>
  <style>
    :root { --bg:#FFFEEC; --brand:#FFF100; --text:#231815; --line:#e8df9a; }
    body { margin:0; min-height:100vh; display:grid; place-items:center; background:var(--bg); color:var(--text); font-family:-apple-system,BlinkMacSystemFont,"Helvetica Neue","Noto Sans TC",Arial,sans-serif; }
    form { width:min(420px, calc(100vw - 32px)); background:#fffef5; border:1px solid var(--line); border-radius:10px; padding:24px; box-shadow:0 10px 30px rgba(35,24,21,.08); }
    h1 { margin:0 0 18px; font-size:26px; }
    label { display:block; font-weight:800; margin:14px 0 6px; }
    input { width:100%; box-sizing:border-box; height:42px; border:1px solid #cfc46d; border-radius:6px; padding:0 10px; font-size:16px; }
    button { width:100%; height:44px; margin-top:20px; border:1px solid var(--text); border-radius:6px; background:var(--brand); color:var(--text); font-weight:900; font-size:16px; cursor:pointer; }
    .error { background:#fff0f0; border:1px solid #f3b0aa; color:#b42318; padding:10px; border-radius:6px; margin-bottom:12px; }
  </style>
</head>
<body>
  <form method="post" action="/login">
    <h1>擺攤收款紀錄</h1>
    {error}
    <label>帳號</label>
    <input name="username" autocomplete="username" autofocus>
    <label>密碼</label>
    <input name="password" type="password" autocomplete="current-password">
    <button type="submit">登入</button>
  </form>
</body>
</html>"""


def db():
    if not DATABASE_URL:
        raise RuntimeError("尚未設定 DATABASE_URL")
    return psycopg.connect(DATABASE_URL, row_factory=dict_row)


def setup_db():
    with db() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS products (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sku TEXT NOT NULL UNIQUE,
                name TEXT NOT NULL,
                style TEXT NOT NULL DEFAULT '',
                unit TEXT NOT NULL DEFAULT '個',
                cost NUMERIC NOT NULL DEFAULT 0,
                price NUMERIC NOT NULL DEFAULT 0,
                active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS sales (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                event_name TEXT NOT NULL DEFAULT '',
                collector TEXT NOT NULL DEFAULT '',
                line_pay BOOLEAN NOT NULL DEFAULT FALSE,
                donation NUMERIC NOT NULL DEFAULT 0,
                sold_on TEXT NOT NULL,
                total_items NUMERIC NOT NULL DEFAULT 0,
                total_amount NUMERIC NOT NULL DEFAULT 0,
                created_at TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS sale_items (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sale_id BIGINT NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
                product_id BIGINT NOT NULL REFERENCES products(id),
                product_name TEXT NOT NULL,
                product_style TEXT NOT NULL DEFAULT '',
                qty NUMERIC NOT NULL,
                unit_price NUMERIC NOT NULL,
                unit_cost NUMERIC NOT NULL DEFAULT 0
            );
