services:
  - type: web
    name: booth-payment-record
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn online_app:app
    envVars:
      - key: APP_USERNAME
        value: admin
      - key: APP_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
